### ISSUE TITLE
Links and <em>, <strong> replacement

### ISSUE THREAD

**Issue by eduramiba** [cletus/jmd#2]
First, I have to thank you for this library. It works really great :D

So, the problem is that sequences like  `_foo_` or `__bar__` , which are really common in links, are replaced for `<em>foo</em>` and `<strong>bar</strong>` in links.

Thanks for your work.

**Comment by emarc** [comment]
I related issue, I think: special chars are replaced with character entities in links as well. 

```
 & -> &amp;
```

It's not obvious how to fix this after a quick look at the source - how to leave the attributes of an links alone? Does it work with "the original" (MarkdownSharp)? 

Still, it's already great, much better than the other options :-)
